version: '3.9'

services: 

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2174583
      POSTGRES_DB: WebShop
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
     - backend

  api:
    build:
      context: ./
      dockerfile: ./SkillForge.Api/Dockerfile
    ports: 
      - "7090:7090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database
      - auth
      - prods
      - talks
      - notif
    networks:
      - backend

  notif:
    build:
      context: ./
      dockerfile: ./SkillForge.Notificator/Dockerfile
    ports: 
      - "7029:7029"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database
      - auth
    networks:
      - backend

  talks:
    build:
      context: ./
      dockerfile: ./SkillForge.Talks/Dockerfile
    ports: 
      - "7134:7134"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database
      - auth
    networks:
      - backend

  prods:
    build:
      context: ./
      dockerfile: ./SkillForge.Products/Dockerfile
    ports: 
      - "7211:7211"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - database
      - auth
    networks:
      - backend

  auth:
    build: 
      context: ./
      dockerfile: ./SkillForge.Auth/Dockerfile

    ports: 
      - "7222:7222"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - database
    networks:
      - backend

volumes: 
  pgdata:

networks:
  backend:
    driver: bridge